name: Build Swift Package

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build-swift-package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Build iOS framework
        id: buildPackage
        run: ./gradlew createSwiftPackage --no-daemon
      - name: Upload Swift Package directory
        uses: actions/upload-artifact@v2
        with:
          name: swiftpackage
          path: shared/swiftpackage
          retention-days: 1

  push-swift-package:
    needs: build-swift-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download directory with swift package
        uses: actions/download-artifact@v2
        with:
          name: swiftpackage
          path: swiftpackage
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'swiftpackage'
          destination-github-username: 'Programistich'
          destination-repository-name: 'KMMHeatshrinkSwiftPackage'
          user-email: dzhos.oleksii@gmail.com
          target-branch: main

  changelog_changes:
    name: "Checking that tag has changed"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get change status for data.env
        id: changed-changelog
        uses: tj-actions/changed-files@v18.7
        with:
          files: .github/workflows/data.env
      - name: Failed if tag not changed
        if: steps.changed-changelog.outputs.any_changed != 'true'
        uses: actions/github-script@v3
        with:
          script: core.setFailed('tag has not changed!')

  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set variables'
        id: vars
        run: |
          export $(cat .github/workflows/data.env | xargs)
          echo "::set-output name=tag::${TAG}"
      - name: Set new tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.vars.outputs.tag }}
